name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for requesting the OIDC token
  contents: read   # Required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Vite site
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::387151115005:role/GitHub-LLHSFinance
          aws-region: us-east-1

      - name: Sync files to S3
        run: aws s3 sync dist/ s3://llhsfinance --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E24U6JG9H5UTJL --paths "/*"